version: "3.9"
services:

  database:
    image: mysql
    env_file:
      - live_trader.env
  live_trader:
    build: src/
    deploy:
      restart_policy: #restart if database is not ready
        condition: on-failure
        delay: 10s
        max_attempts: 15

    depends_on:
      - db
    env_file:
      - live_trader.env
