version: "3.9"

services:
  live_trader:
    image: live_trader
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - live_trader.env
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/main.py "
      ]
    ports:
      - 5678:5678
    depends_on:
      database:
        condition: service_healthy
  database:
    image: x11tete11x/arm32v7-mysql:latest
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    env_file:
      - live_trader.env
