version: "3.9"
services:

  database:
    image: mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    env_file:
      - live_trader.env
  live_trader:
    build: src/
    depends_on:
        database:
            condition: service_healthy
    env_file:
      - live_trader.env
