version: "3.9"

services:
  live_trader:
    image: live_trader
    build:
      context: .
      dockerfile: ./live_trader.Dockerfile
    env_file:
      - live_trader.env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: x11tete11x/arm32v7-mysql:latest
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    env_file:
      - live_trader.env

  #testing
  tester:
    image: tester
    build:
      context: .
      dockerfile: ./tester.Dockerfile
    env_file:
      - live_trader.env
    depends_on:
      database:
        condition: service_healthy
